language: php

php:
  - 5.6.4
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.4.*
  - LARAVEL_VERSION=5.5.*
  - LARAVEL_VERSION=5.6.*

matrix:
  # For each PHP version we exclude the coverage env, except for PHP 7.2
  exclude:
    - php: 5.6.4
      env: LARAVEL_VERSION=5.4.* PHPUNIT_VERSION=~6
    # Test only Laravel 5.5, 5.6 on PHP 7.0
    - php: 7.0
      env: LARAVEL_VERSION=5.5.* PHPUNIT_VERSION=~7.0
    - php: 7.0
      env: LARAVEL_VERSION=5.6.* PHPUNIT_VERSION=~7.0
    # Test only Laravel 5.4, 5.5, 5.6 on PHP 7.1
    - php: 7.1
      env: LARAVEL_VERSION=5.4.* PHPUNIT_VERSION=~7.0
    - php: 7.1
      env: LARAVEL_VERSION=5.5.* PHPUNIT_VERSION=~7.0
    - php: 7.1.3
      env: LARAVEL_VERSION=5.6.* PHPUNIT_VERSION=~7.0
    - php: 7.2
      env: LARAVEL_VERSION=5.6.* PHPUNIT_VERSION=~7.0 COVERAGE=true

sudo: false

before_install:
  - composer self-update
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
  - phpenv config-rm xdebug.ini
  - composer require "laravel/laravel:${LARAVEL_VERSION}" --no-update --prefer-dist
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install:
  - composer update --no-interaction --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp

after_success:
  - php vendor/bin/coveralls
